fix github action

diff --git a/.github/workflows/build-boxkit.yml b/.github/workflows/build-boxkit.yml
--- a/.github/workflows/build-boxkit.yml
+++ b/.github/workflows/build-boxkit.yml
@@ -4,16 +4,16 @@ on:
     branches:
       - main
   schedule:
-    - cron: '0 0 * * TUE'
+    - cron: "0 0 * * TUE"
   push:
     branches:
       - main
     paths-ignore:
-      - '**/README.md'
+      - "**/README.md"
 env:
-    IMAGE_NAME: boxkit
-    IMAGE_TAGS: latest
-    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
+  IMAGE_NAME: boxkit
+  IMAGE_TAGS: latest
+  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
 
 jobs:
   push-ghcr:
@@ -25,11 +25,11 @@ jobs:
       id-token: write
     strategy:
       fail-fast: false
-    steps: 
+    steps:
       # Checkout push-to-registry action GitHub repository
       - name: Checkout Push to Registry action
         uses: actions/checkout@v3
-        
+
       # Build metadata
       - name: Image Metadata
         uses: docker/metadata-action@v4
@@ -51,7 +51,7 @@ jobs:
           tags: ${{ env.IMAGE_TAGS }}
           labels: ${{ steps.meta.outputs.labels }}
           oci: false
-          
+
       # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
       # https://github.com/macbre/push-to-ghcr/issues/12
       - name: Lowercase Registry
@@ -75,14 +75,14 @@ jobs:
           password: ${{ env.REGISTRY_PASSWORD }}
           extra-args: |
             --disable-content-trust
-            
+
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-            
+
       # Sign container
       - uses: sigstore/cosign-installer@v3.0.1
 
@@ -99,3 +99,11 @@ jobs:
       - name: Echo outputs
         run: |
           echo "${{ toJSON(steps.push.outputs) }}"
+
+      - name: Test secret
+        run: |
+          if [ -z "${{ secrets.SIGNING_SECRET }}" ]; then
+            echo "Secret SIGNING_SECRET not found!"
+            exit 1
+          fi
+          echo "Secret SIGNING_SECRET found: ${{ secrets.SIGNING_SECRET }}"
